# Generated by Django 4.2.1 on 2023-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dismissal_date',
            field=models.DateField(null=True, verbose_name='Дата увольнения'),
        ),
    ]
