# Generated by Django 4.2.1 on 2023-05-14 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0005_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Оклад'),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала отпуска')),
                ('end_date', models.DateField(verbose_name='Дата окончания отпуска')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Размер выплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Процент начисления')),
                ('base_pay', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Тарифная ставка')),
                ('start_date', models.DateField(verbose_name='Дата начала больничного')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания больничного')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Размер выплаты')),
                ('type', models.CharField(choices=[('kid', 'По уходу за ребенком'), ('ill', 'В связи с болезнью'), ('pregnancy', 'По беременности и родам'), ('other', 'Другое')], max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField(blank=True, null=True, verbose_name='Размер премии')),
                ('payment_date', models.DateField(verbose_name='Дата выплаты')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Итоговая сумма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
